// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, AccountId32Like } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from 'dedot/contracts';
import type { Challenge5ContractDaoError, InkPrimitivesLangError } from './types';

export interface ContractQuery<ChainApi extends GenericSubstrateApi> extends GenericContractQuery<ChainApi> {
  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x81b2cf8b
   **/
  registerVoter: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Challenge5ContractDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xa4279724
   **/
  deregisterVoter: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Challenge5ContractDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {AccountId32Like} voter
   * @param {ContractCallOptions} options
   *
   * @selector 0xf7156a78
   **/
  hasVoter: GenericContractQueryCall<
    ChainApi,
    (
      voter: AccountId32Like,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x547cc8db
   **/
  createSuperdaoCrossChainProposal: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Challenge5ContractDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x0071768f
   **/
  createContractCallProposal: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Challenge5ContractDaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} proposalId
   * @param {boolean} vote
   * @param {ContractCallOptions} options
   *
   * @selector 0x946595e4
   **/
  voteProposal: GenericContractQueryCall<
    ChainApi,
    (
      proposalId: number,
      vote: boolean,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Challenge5ContractDaoError>, ContractCallResult<ChainApi>>>
  >;
}
