// Generated by dedot cli

import type { AccountId32 } from 'dedot/codecs';

export type InkStorageLazyVecStorageVec = { len: InkStorageLazy; elements: InkStorageLazyMapping };

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type InkStorageLazy = {};

export type InkStorageLazyMapping = {};

export type Challenge5ContractDao = { superdao: AccountId32; name: string; voters: InkStorageLazyVecStorageVec };

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type MinidaoCommonDaoError =
  | { type: 'VoterAlreadyRegistered' }
  | { type: 'VoterNotRegistered' }
  | { type: 'VoterAlreadyVoted' }
  | { type: 'ProposalDoesNotExist' }
  | { type: 'PrevotePeriodIsNotEnded' }
  | { type: 'NoContractAddress' }
  | { type: 'SuperdaoError'; value: SuperdaoTraitsError };

export type SuperdaoTraitsError = 'DispatchFailed' | 'AlreadyMember' | 'NotMember' | 'ProposalNotFound';

export type InkEnvNoChainExtension = null;
