// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Result, AccountId32 } from 'dedot/codecs';
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from 'dedot/contracts';
import type {
  InkPrimitivesLangError,
  Superda0TraitsSuperdaoError,
  Superda0TraitsSuperdaoCallLike,
  Superda0TraitsSuperdaoVote,
  Superda0TraitsSuperdaoProposal,
} from './types';

export interface ContractQuery<ChainApi extends GenericSubstrateApi> extends GenericContractQuery<ChainApi> {
  /**
   *
   * @param {number} propId
   * @param {ContractCallOptions} options
   *
   * @selector 0x78e3d8b2
   **/
  resolveProposal: GenericContractQueryCall<
    ChainApi,
    (
      propId: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x234726e7
   **/
  superDaoRegisterMember: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Superda0TraitsSuperdaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0xba5e25a8
   **/
  superDaoDeregisterMember: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<[], ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {Superda0TraitsSuperdaoCallLike} call
   * @param {ContractCallOptions} options
   *
   * @selector 0x7c5f540f
   **/
  superDaoCreateProposal: GenericContractQueryCall<
    ChainApi,
    (
      call: Superda0TraitsSuperdaoCallLike,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Superda0TraitsSuperdaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} propId
   * @param {Superda0TraitsSuperdaoVote} vote
   * @param {ContractCallOptions} options
   *
   * @selector 0x5002b426
   **/
  superDaoVote: GenericContractQueryCall<
    ChainApi,
    (
      propId: number,
      vote: Superda0TraitsSuperdaoVote,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Result<[], Superda0TraitsSuperdaoError>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x51565355
   **/
  superDaoQueryGetMembers: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<AccountId32>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x77f94f7a
   **/
  superDaoQueryIsMember: GenericContractQueryCall<
    ChainApi,
    (options?: ContractCallOptions) => Promise<GenericContractCallResult<boolean, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} index
   * @param {ContractCallOptions} options
   *
   * @selector 0x1421bc5e
   **/
  superDaoQueryGetProposal: GenericContractQueryCall<
    ChainApi,
    (
      index: number,
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Superda0TraitsSuperdaoProposal | undefined, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x8e77186a
   **/
  superDaoQueryGetProposals: GenericContractQueryCall<
    ChainApi,
    (
      options?: ContractCallOptions,
    ) => Promise<GenericContractCallResult<Array<Superda0TraitsSuperdaoProposal>, ContractCallResult<ChainApi>>>
  >;

  /**
   *
   * @param {number} proposalId
   * @param {ContractCallOptions} options
   *
   * @selector 0x19278efe
   **/
  superDaoQueryGetVotes: GenericContractQueryCall<
    ChainApi,
    (
      proposalId: number,
      options?: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<Array<[AccountId32, Superda0TraitsSuperdaoVote]>, ContractCallResult<ChainApi>>
    >
  >;
}
