// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from 'dedot/contracts';
import type { Superda0TraitsSuperdaoCallLike, Superda0TraitsSuperdaoVote } from './types';

export interface ContractTx<ChainApi extends GenericSubstrateApi> extends GenericContractTx<ChainApi> {
  /**
   *
   * @param {number} propId
   * @param {ContractTxOptions} options
   *
   * @selector 0x78e3d8b2
   **/
  resolveProposal: GenericContractTxCall<
    ChainApi,
    (propId: number, options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x234726e7
   **/
  superDaoRegisterMember: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0xba5e25a8
   **/
  superDaoDeregisterMember: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {Superda0TraitsSuperdaoCallLike} call
   * @param {ContractTxOptions} options
   *
   * @selector 0x7c5f540f
   **/
  superDaoCreateProposal: GenericContractTxCall<
    ChainApi,
    (call: Superda0TraitsSuperdaoCallLike, options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {number} propId
   * @param {Superda0TraitsSuperdaoVote} vote
   * @param {ContractTxOptions} options
   *
   * @selector 0x5002b426
   **/
  superDaoVote: GenericContractTxCall<
    ChainApi,
    (
      propId: number,
      vote: Superda0TraitsSuperdaoVote,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
